version: '3.8'
services:
  myblog_server:
    build: .
    image: myblog
    container_name: myblog_server
    ports:
      - "82:10087"
    links:
      - mysql_server
    environment:
      MYSQL_HOST: mysql_server
      MYSQL_DB: myblog_db
      MYSQL_USER: root
      MYSQL_PWD: nevertellyou
      volumes:
    volumes:
      - /opt/myblog_data:/opt/myblog/data
    depends_on:
      mysql_server:
        condition: service_healthy
  mysql_server:
    image: mysql:8.0
    container_name: mysql_server
    volumes:
      - /opt/mysql_of_blog:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nevertellyou
      MYSQL_DATABASE: myblog_db
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      